# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170219_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_taken_test',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
